import Anthropic from '@anthropic-ai/sdk'

export const runtime = 'edge'

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
})

// Build the prompt based on user options
function buildPrompt({ framework, styling, instructions }) {
  const frameworkMap = {
    react:  'React (functional components with hooks)',
    nextjs: 'Next.js 14 with App Router (use "use client" where needed)',
    vue:    'Vue 3 with Composition API (<script setup>)',
  }
  const stylingMap = {
    tailwind:   'Tailwind CSS utility classes',
    cssmodules: 'CSS Modules (styles.module.css)',
    styled:     'Styled Components (styled-components library)',
  }

  const fw = frameworkMap[framework] || frameworkMap.react
  const st = stylingMap[styling]     || stylingMap.tailwind

  return `You are an expert frontend developer. Analyze this UI screenshot or design and generate clean, production-ready component code.

REQUIREMENTS:
- Framework: ${fw}
- Styling: ${st}
- Make it fully responsive
- Use semantic HTML elements
- Include all visible UI elements, text, icons (use inline SVGs for icons)
- Match the layout, spacing, colors, and typography as closely as possible
- Add smooth hover states and transitions where appropriate
- Export the component as default export
${instructions ? `\nEXTRA INSTRUCTIONS FROM USER:\n${instructions}` : ''}

OUTPUT FORMAT:
- Return ONLY the component code — no explanations, no markdown code fences, no preamble
- Start directly with the import statements or component definition
- The code must be complete and ready to copy-paste and run
- Include a brief comment at the top: // Generated by design.code — claude-sonnet-4-5

Analyze every detail of the design: layout structure, color palette, typography, spacing, interactive elements, and generate pixel-perfect code.`
}

export async function POST(request) {
  try {
    const body = await request.json()
    const { imageBase64, imageType, framework, styling, instructions } = body

    // Validate
    if (!imageBase64) {
      return new Response(JSON.stringify({ error: 'No image provided' }), {
        status: 400,
        headers: { 'Content-Type': 'application/json' },
      })
    }
    if (!process.env.ANTHROPIC_API_KEY) {
      return new Response(JSON.stringify({ error: 'ANTHROPIC_API_KEY is not set in environment variables' }), {
        status: 500,
        headers: { 'Content-Type': 'application/json' },
      })
    }

    const prompt = buildPrompt({ framework, styling, instructions })

    // Create a streaming response
    const stream = new ReadableStream({
      async start(controller) {
        const encoder = new TextEncoder()

        try {
          const anthropicStream = await client.messages.stream({
            model: 'claude-sonnet-4-5',
            max_tokens: 8192,
            messages: [
              {
                role: 'user',
                content: [
                  {
                    type: 'image',
                    source: {
                      type: 'base64',
                      media_type: imageType || 'image/png',
                      data: imageBase64,
                    },
                  },
                  {
                    type: 'text',
                    text: prompt,
                  },
                ],
              },
            ],
          })

          // Stream each text delta to the client
          for await (const event of anthropicStream) {
            if (
              event.type === 'content_block_delta' &&
              event.delta.type === 'text_delta'
            ) {
              const chunk = JSON.stringify({ type: 'delta', text: event.delta.text }) + '\n'
              controller.enqueue(encoder.encode(chunk))
            }

            if (event.type === 'message_stop') {
              const done = JSON.stringify({ type: 'done' }) + '\n'
              controller.enqueue(encoder.encode(done))
            }

            if (event.type === 'message_start') {
              const start = JSON.stringify({ type: 'start' }) + '\n'
              controller.enqueue(encoder.encode(start))
            }
          }
        } catch (err) {
          const error = JSON.stringify({
            type: 'error',
            message: err.message || 'Claude API error',
          }) + '\n'
          controller.enqueue(encoder.encode(error))
        } finally {
          controller.close()
        }
      },
    })

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Transfer-Encoding': 'chunked',
        'Cache-Control': 'no-cache',
        'X-Content-Type-Options': 'nosniff',
      },
    })
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err.message || 'Unexpected server error' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    )
  }
}