import Anthropic from '@anthropic-ai/sdk'

export const runtime = 'edge'

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

function buildPrompt({ framework, styling, instructions }) {
  const frameworkMap = {
    react:  'React (functional components with hooks)',
    nextjs: 'Next.js 14 with App Router (use "use client" where needed)',
    vue:    'Vue 3 with Composition API (<script setup>)',
  }
  const stylingMap = {
    tailwind:   'Tailwind CSS utility classes',
    cssmodules: 'CSS Modules (component.module.css)',
    styled:     'Styled Components (styled-components library)',
  }

  const fw  = frameworkMap[framework] || frameworkMap.react
  const st  = stylingMap[styling]     || stylingMap.tailwind
  const ext = framework === 'vue' ? 'vue' : 'jsx'

  // CSS Modules needs an actual styles file; Tailwind/Styled do not
  const needsStylesFile = styling === 'cssmodules'

  return `You are an expert frontend developer. Analyze this UI screenshot and generate a complete, production-ready component split across multiple files.

REQUIREMENTS:
- Framework: ${fw}
- Styling: ${st}
- Fully responsive, semantic HTML, smooth hover states and transitions
- Include all visible UI elements, text, icons (inline SVGs)
- Match layout, spacing, colors, and typography as closely as possible
- Export the main component as default export
${instructions ? `\nEXTRA INSTRUCTIONS:\n${instructions}\n` : ''}
OUTPUT FORMAT — return a single valid JSON object with exactly these keys:
{
  "component": "<full ${ext} component code>",
  "styles": "${needsStylesFile ? '<full CSS for component.module.css>' : 'null — not needed for this styling system'}",
  "test": "<full Jest + React Testing Library test file for the component>",
  "index": "export { default } from './Component';"
}

RULES:
- Return ONLY the raw JSON object — no markdown fences, no explanation, no text before or after
- Every value must be a valid JSON string (escape newlines as \\n, quotes as \\")
- The "component" file must be complete and runnable on its own
- The "test" file must import the component as: import Component from './Component'
- Add this comment at the top of the component: // Generated by design.code
- If styling is NOT cssmodules, set "styles" to null`
}

export async function POST(request) {
  try {
    const body = await request.json()
    const { imageBase64, imageType, framework, styling, instructions } = body

    if (!imageBase64) {
      return new Response(JSON.stringify({ error: 'No image provided' }), {
        status: 400, headers: { 'Content-Type': 'application/json' },
      })
    }
    if (!process.env.ANTHROPIC_API_KEY) {
      return new Response(JSON.stringify({ error: 'ANTHROPIC_API_KEY is not set' }), {
        status: 500, headers: { 'Content-Type': 'application/json' },
      })
    }

    const prompt = buildPrompt({ framework, styling, instructions })

    const stream = new ReadableStream({
      async start(controller) {
        const encoder = new TextEncoder()
        try {
          const anthropicStream = await client.messages.stream({
            model: 'claude-sonnet-4-5',
            max_tokens: 8192,
            messages: [{
              role: 'user',
              content: [
                {
                  type: 'image',
                  source: { type: 'base64', media_type: imageType || 'image/png', data: imageBase64 },
                },
                { type: 'text', text: prompt },
              ],
            }],
          })

          for await (const event of anthropicStream) {
            if (event.type === 'message_start') {
              controller.enqueue(encoder.encode(JSON.stringify({ type: 'start' }) + '\n'))
            }
            if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') {
              controller.enqueue(encoder.encode(JSON.stringify({ type: 'delta', text: event.delta.text }) + '\n'))
            }
            if (event.type === 'message_stop') {
              controller.enqueue(encoder.encode(JSON.stringify({ type: 'done' }) + '\n'))
            }
          }
        } catch (err) {
          controller.enqueue(encoder.encode(JSON.stringify({ type: 'error', message: err.message }) + '\n'))
        } finally {
          controller.close()
        }
      },
    })

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Transfer-Encoding': 'chunked',
        'Cache-Control': 'no-cache',
      },
    })
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err.message || 'Unexpected error' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    )
  }
}